### ISSUE TITLE
Question: Why multiprocessing?

### ISSUE THREAD

**Issue by signorrayan** [ThusInfinity/Dark-Matter-Layer-7-DDoS#15]
Why you are using multiprocessing, instead of multithreading?
In some machines, user-space processes are limited for each user, and the multiprocessing will exceed the limit.
for stressing tools, i think it is a good idea to use both multiprocessing and multi threading. (maybe i'm wrong!).
For example 10 process which have 10000 thread each.

**Comment by ThusInfinity** [comment]
> In some machines, user-space processes are limited for each user, and the multiprocessing will exceed the limit.

Yes, using multithreading would be also faster....
But if you use multithreading, most of the VPSes/Servers would lag the CPU when creating and starting 5000 threads at once, so it would slow down the socket creation/connection and would make the connections and the requests slower **(It would be like stressing the client instead of the server)**
In contrast, multiprocessing can start 5000 threads at once without CPU Lag... In addition, the python GIL wont let 2 threads run at same time, but multiprocessing does not deal with this problem, so it can run 2 multiprocessses at same time (or 5000 aswell).

**Comment by signorrayan** [comment]
Thank you for explaining, I should try both of these and see which has a better proof of concept.
